# Generated by Django 4.2.7 on 2025-09-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='phone_number',
            field=models.CharField(default='exit', max_length=15),
            preserve_default=False,
        ),
    ]
