# Generated by Django 4.2.7 on 2025-12-31 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_deliveryperson'),
        ('orders', '0002_savedcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='actual_delivery_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_location',
            field=models.JSONField(blank=True, help_text="Stores lat/lng as {'lat': 0.0, 'lng': 0.0}", null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to='accounts.deliveryperson'),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_delivery_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='eta',
            field=models.DateTimeField(blank=True, help_text='Estimated time of arrival', null=True),
        ),
        migrations.CreateModel(
            name='DeliveryTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('preparing', 'Preparing'), ('ready', 'Ready for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('current_location', models.JSONField(blank=True, help_text="Stores lat/lng as {'lat': 0.0, 'lng': 0.0}", null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('delivery_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.deliveryperson')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='orders.order')),
            ],
            options={
                'verbose_name_plural': 'Delivery Tracking',
            },
        ),
    ]
