# Generated by Django 4.2.7 on 2025-12-31 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_actual_delivery_time_order_delivery_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverytracking',
            name='current_location',
            field=models.JSONField(blank=True, help_text="Stores location as {'lat': 0.0, 'lng': 0.0}", null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_location',
            field=models.JSONField(blank=True, help_text="Stores location as {'lat': 0.0, 'lng': 0.0}", null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='eta',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
