# Generated by Django 4.2.7 on 2025-09-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiffins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiffinservice',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Visible to customers only after admin approval'),
        ),
    ]
