# Generated by Django 4.2.7 on 2026-02-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiffins', '0002_tiffinservice_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiffinservice',
            name='image',
            field=models.ImageField(default='exit', upload_to='tiffins/'),
            preserve_default=False,
        ),
    ]
